on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Build 
      run: NODE_ENV=production pnpm build
    - run: echo `git rev-parse HEAD` > dist/COMMIT
    - name: Upload Build Result
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
    - name: Download Build Result
      uses: actions/download-artifact@v4
      with:
        name: dist
    # upload to dist branch
    - uses: actions/checkout@v2
      with:
        ref: dist
        path: ./dist-branch
    - run: rm -rf ./dist-branch/* && cp -r ./dist/* ./dist-branch/
    - run: |
        COMMIT=`cat dist/COMMIT`
        cd dist-branch
        rm COMMIT
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A .
        git commit --allow-empty -m "update with $COMMIT"
        git push
